config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :loads
  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :loads
end
  

app/models/load.rb
class Load < ApplicationRecord
    belongs_to :customer
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :address, :phone, :email)
    end
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :set_load, only: %i[ show edit update destroy ]

  # GET /loads or /loads.json
  def index
    @loads = Load.all
  end

  # GET /loads/1 or /loads/1.json
  def show
  end

  # GET /loads/new
  def new
    @load = Load.new
  end

  # GET /loads/1/edit
  def edit
  end

  # POST /loads or /loads.json
  def create
    @load = Load.new(load_params)

    respond_to do |format|
      if @load.save
        format.html { redirect_to load_url(@load), notice: "Load was successfully created." }
        format.json { render :show, status: :created, location: @load }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loads/1 or /loads/1.json
  def update
    respond_to do |format|
      if @load.update(load_params)
        format.html { redirect_to load_url(@load), notice: "Load was successfully updated." }
        format.json { render :show, status: :ok, location: @load }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loads/1 or /loads/1.json
  def destroy
    @load.destroy

    respond_to do |format|
      format.html { redirect_to loads_url, notice: "Load was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_load
      @load = Load.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def load_params
      params.require(:load).permit(:origin, :destination, :pickup_date, :delivery_date, :status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customers/_customer.html.erb
<html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<body>
<div class="container" >
<div id="<%= dom_id customer %>" class="card">
  <div class="card-body">
    <h5 class="card-title"><%= customer.name %></h5>
    <p class="card-text"><strong>Address:</strong> <%= customer.address %></p>
    <p class="card-text"><strong>Phone:</strong> <%= customer.phone %></p>
    <p class="card-text"><strong>Email:</strong> <%= customer.email %></p>
  </div>
</div>
</div>
</body>
</html>

app/views/customers/_form.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<%= form_with(model: customer, class: "my-4") do |form| %>
  <% if customer.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", customers_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<p style="color: green"><%= notice %></p>

<h1 class="text-center" >Customers</h1>

<div class="container" id="customers">
  <% @customers.each do |customer| %>
    <%= render customer %>
    <p>
      <%= link_to "Show this customer", customer, class: "btn btn-primary col-2", style: "" %>
    </p>
  <% end %>
</div>

<div class="card-footer text-center">
  <%= link_to "New customer", new_customer_path, class: "btn btn-primary col-2", style: "" %>
  <%= link_to "All loads", loads_path, class: "btn btn-danger col-2", style: "" %>
  <%= link_to 'Homepage', root_path, class: "btn btn-secondary col-2", style: "" %>
</div>

app/views/customers/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New customer</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
  <body>
    <div class="container">
      <h1 class="my-4">New customer</h1>

      <%= render "form", customer: @customer %>

      <div class="mt-4">
        <%= link_to "All loads", loads_path, class: 'btn btn-secondary me-2' %>
        <%= link_to "All customers", customers_path, class: 'btn btn-secondary me-2' %>
        <%= link_to 'Homepage', root_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </body>
</html>

app/views/customers/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Customer List</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <p class="alert alert-success"><%= notice %></p>

  <div class="card">
    <div class="card-header">
      <h5 class="card-title">Customer Details</h5>
    </div>
    <div class="card-body">
      <%= render @customer %>
    </div>
    <div class="card-footer">
      <%= link_to "Edit", edit_customer_path(@customer), class: "btn btn-primary col-2", style: "" %>
      <%= button_to "Delete", @customer, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger auto col-2", style: "" %>
      <%= link_to "Back to Customers", customers_path, class: "btn btn-secondary col-2", style: "" %>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <title>MovensresDispatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loads/_form.html.erb
<div class="container">
<%= form_with(model: load) do |form| %>
  <% if load.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(load.errors.count, "error") %> prohibited this load from being saved:</h2>

      <ul>
        <% load.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="form-group">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.all, :id, :name, prompt: true %>
  </div>


  <div>
    <%= form.label :origin, style: "display: block" %>
    <%= form.text_field :origin %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :pickup_date, style: "display: block" %>
    <%= form.date_field :pickup_date %>
  </div>

  <div>
    <%= form.label :delivery_date, style: "display: block" %>
    <%= form.date_field :delivery_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/loads/_load.html.erb
<div id="<%= dom_id load %>">
  <p>
    <strong>Origin:</strong>
    <%= load.origin %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= load.destination %>
  </p>

  <p>
    <strong>Pickup date:</strong>
    <%= load.pickup_date %>
  </p>

  <p>
    <strong>Delivery date:</strong>
    <%= load.delivery_date %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= load.status %>
  </p>

</div>

app/views/loads/edit.html.erb
<h1>Editing load</h1>

<%= render "form", load: @load %>

<br>

<div>
  <%= link_to "Show this load", @load %> |
  <%= link_to "Back to loads", loads_path %>
</div>

app/views/loads/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div class="container">
  <h1 class="mt-5">All Loads</h1>

  <a class="btn btn-primary mb-3" href="/loads/new">New Load</a>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Customer</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Pick Up Date</th>
        <th>Delivery Date</th>
        <th>Status</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @loads.each do |load| %>
        <tr>
          <td><%= load.customer %></td>
          <td><%= load.origin %></td>
          <td><%= load.destination %></td>
          <td><%= load.pickup_date %></td>
          <td><%= load.delivery_date %></td>
          <td><%= load.status %></td>
          <td><%= link_to 'Show', load, class: 'btn btn-sm btn-outline-secondary' %></td>
          <td><%= link_to 'Edit', edit_load_path(load), class: 'btn btn-sm btn-outline-primary' %></td>
          <td><%= link_to 'Destroy', load, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "All customers", customers_path, class: 'btn btn-secondary mb-3' %>
  <%= link_to 'Homepage', root_path, class: 'btn btn-primary mb-3' %>
</div>

app/views/loads/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Loads</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
  <body>
      <div class="container">
        <h1>New load</h1>

        <%= render "form", load: @load %>

        <br>
        <div class="">
          <%= link_to "All loads", loads_path, class: 'btn btn-primary' %>
          <%= link_to "All customers", customers_path, class: 'btn btn-danger' %>
          <%= link_to 'Homepage', root_path, class: 'btn btn-secondary' %>

        </div>
      </div>

  </body>
</html>

app/views/loads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @load %>

<p>
  <strong>Customer:</strong>
  <%= @load.customer %>
</p>


<div>
  <%= link_to "Edit this load", edit_load_path(@load) %> |
  <%= link_to "Back to loads", loads_path %>

  <%= button_to "Destroy this load", @load, method: :delete %>
</div>

app/views/pages/home.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-5 text-center">
      <h1 class="mb-5">MovensRes Trucking Dispatch CRM</h1>
      <%= link_to 'Create a Load', new_load_path, class: "btn btn-primary btn-lg d-block mx-auto mb-4" %>
      <%= link_to 'View All Loads', loads_path, class: "btn btn-secondary btn-sm d-block mx-auto mb-4" %>
      <hr class="my-4">
      <%= link_to 'Create Customer', new_customer_path, class: "btn btn-primary btn-lg d-block mx-auto mb-4" %>
      <%= link_to 'View All Customers', customers_path, class: "btn btn-secondary btn-sm d-block mx-auto mb-4" %>
    </div>
  </div>
</div>